# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 060e502b08c3b3364b7ae1efeb01e145a10778bf9928cb0a239f4b68c88dfdd7422fc680410943778ddf3a952ae33d64a0236b319a20224ba1560c2d76070d83

test:
  secret_key_base: 912d1e5181a4efb49a13b822136589bf7e6036c21c60f4d4dce9961be6fc87aedaf9b3c1bd22eb7bfbf271b9aaa9cc4b2cd300a463610b599f5cba7170618a55

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
